services:

  web:
    restart: always
    # build: ./mlflow
    image: mlflow_server
    container_name: mlflow_server
    # networks:
      # - frontend
      # - backend
    expose:
      - "5000"

    command: mlflow server --backend-store-uri=sqlite:///mlflow_db.db --default-artifact-root=sqlite:///mlflow_db.db --host=0.0.0.0 --port=5000


  db:
    image: nouchka/sqlite3
    container_name: mlflow_db
    # networks:
    #   - backend

  nginx:
    restart: always
    build: ./nginx
    image: mlflow_nginx
    container_name: mlflow_nginx
    ports:
      - "80:80"
    # networks:
    #   - frontend
    depends_on:
      - web



  # networks:
  #   frontend-network:
  #     external: true