name: mlflow-env

channels:
- conda-forge
dependencies:
- python=3.7.
- pip<=21.2.4
- pip:
  - mlflow
  - cloudpickle==2.1.0
  - mypy-extensions==0.4.3
  - psutil==5.9.1
  - scikit-learn==1.0.2
  - xgboost==1.5.0
